# Generated by Django 3.0.5 on 2021-03-27 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20210324_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, null=True, unique=True),
        ),
    ]
