# Generated by Django 3.0.5 on 2021-03-27 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20210327_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('1f677f90-4856-4de5-9959-2b45c7b67036'), max_length=36, null=True, unique=True),
        ),
    ]
